<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Carrot - 1 Kg56ADD TO CART</name>
   <tag></tag>
   <elementGuidId>06be0678-4162-4097-86b7-ddfabf8679fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.product</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e564376a-7be6-49d9-adba-f49bc1f9f355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product</value>
      <webElementGuid>2a2a4a61-39bd-47d8-91e3-ed605be035b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Carrot - 1 Kg56–+ADD TO CART</value>
      <webElementGuid>2ac78cc2-3910-437a-817b-50731bdd74ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;products-wrapper&quot;]/div[@class=&quot;products&quot;]/div[@class=&quot;product&quot;]</value>
      <webElementGuid>5f770841-6381-4427-995d-b93e0d050dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div</value>
      <webElementGuid>b8545a95-b556-4ff5-9ee2-3a063bbbb447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCEED TO CHECKOUT'])[1]/following::div[3]</value>
      <webElementGuid>71e2c713-3ef4-4514-ae81-2d80fdba798e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You cart is empty!'])[1]/following::div[8]</value>
      <webElementGuid>cb8b6723-739e-4188-bd75-9c517c7d1f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div</value>
      <webElementGuid>553410cd-76a0-4c62-b081-0517e71928e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Carrot - 1 Kg56–+ADD TO CART' or . = 'Carrot - 1 Kg56–+ADD TO CART')]</value>
      <webElementGuid>05dd710f-8c66-471a-8737-8edc14bc4ce4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
