<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Hover Over Me First</name>
   <tag></tag>
   <elementGuidId>740c1ef0-2e9b-4460-9371-c9e319b5a4a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div-hover']/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.dropbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fed443c-69ae-4472-b0f5-96ed0b0bf501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropbtn</value>
      <webElementGuid>bcae455b-9a77-43c5-a854-a378f2fc98c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hover Over Me First!</value>
      <webElementGuid>6730a5de-28af-4aac-a8f6-156c71eb4340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div-hover&quot;)/div[@class=&quot;dropdown hover&quot;]/button[@class=&quot;dropbtn&quot;]</value>
      <webElementGuid>e28cb1c2-c94f-4be1-8d61-4ccea5c0948e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-hover']/div/button</value>
      <webElementGuid>8944bef2-56b8-4471-8bf3-944fccedeead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Double Click Me!'])[1]/following::button[1]</value>
      <webElementGuid>d6485080-6ecf-4e3b-ab51-852a874551dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropped!'])[1]/following::button[1]</value>
      <webElementGuid>49304910-de6f-4da0-976b-669000557784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hover Over Me Second!'])[1]/preceding::button[1]</value>
      <webElementGuid>15c5e3bf-b854-4b47-9a27-fbca85cc314f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hover Over Me Third!'])[1]/preceding::button[2]</value>
      <webElementGuid>df858250-4398-45b7-9c35-5b5602f4ecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hover Over Me First!']/parent::*</value>
      <webElementGuid>113a0ef1-36e2-4f42-beb1-bf234e1f86c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/button</value>
      <webElementGuid>620e054b-f2e7-40eb-ba27-c58e7f3d5963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Hover Over Me First!' or . = 'Hover Over Me First!')]</value>
      <webElementGuid>ecd6dc37-c207-4b97-9f75-f1504972a0c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
