<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d5d83490-e6c7-4bd0-866e-4d08a5589ef0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div[3]/a[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35c468fb-d562-461d-95af-c82c623305c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://res.cloudinary.com/sivadass/image/upload/v1493548928/icons/bag.png</value>
      <webElementGuid>1af5712f-c3ef-4c15-ad9c-f9c35dd614df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cart</value>
      <webElementGuid>6f592d05-5a6b-4b7c-854c-9f4ea9f84fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/header[1]/div[@class=&quot;container&quot;]/div[@class=&quot;cart&quot;]/a[@class=&quot;cart-icon&quot;]/img[@class=&quot;&quot;]</value>
      <webElementGuid>2aadf024-9e0f-4829-940c-3653cc0f32e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[3]/a[4]/img</value>
      <webElementGuid>1b4984c3-3167-48ff-8e16-4901e1905d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cart']</value>
      <webElementGuid>5fda33f2-35ac-46e8-8bb4-9a7e2bfb876b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/img</value>
      <webElementGuid>dd415af1-5cdf-4b8e-8b37-800c222ac170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://res.cloudinary.com/sivadass/image/upload/v1493548928/icons/bag.png' and @alt = 'Cart']</value>
      <webElementGuid>7b299e5f-6996-4fa8-89bf-2a6183fb28df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
