<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_WebdriverUniversity.com (New Approach To )</name>
   <tag></tag>
   <elementGuidId>b8e46c8b-6d8b-443a-8540-37c6b18b939e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='nav-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#nav-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5719be70-0f9c-455a-bcce-85de7a94b51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navbar-brand</value>
      <webElementGuid>4066ad52-566d-4e84-bb64-5b7275c21d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nav-title</value>
      <webElementGuid>6100ef6d-345f-4aef-8301-c8a6c38fb5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>index.html</value>
      <webElementGuid>4398ac92-b6f3-4b83-bca7-06d64a8d22af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>WebdriverUniversity.com (New Approach To Learning)</value>
      <webElementGuid>de66ba11-0b62-433d-b63f-0d721bc36baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav-title&quot;)</value>
      <webElementGuid>16b4c140-418d-408e-a57c-e146277713c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='nav-title']</value>
      <webElementGuid>8b9b7d12-6245-47fd-a4b8-30489dfb221e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'WebdriverUniversity.com (New Approach To Learning)')]</value>
      <webElementGuid>5c0b3391-f9bb-40ca-9206-114cfbdc93cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::a[1]</value>
      <webElementGuid>c0a36d43-4e4c-4e85-ab45-f5ae8cb40db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Courses &amp; Promo Codes'])[1]/preceding::a[1]</value>
      <webElementGuid>0ae8fdbf-4e79-44b2-96c3-9438503e3394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='WebdriverUniversity.com (New Approach To Learning)']/parent::*</value>
      <webElementGuid>04903217-9f89-4d35-8e5e-4598540d59fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'index.html')]</value>
      <webElementGuid>d78e5249-4218-4af5-aa03-d0a2b4e7844c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>cbfd4a57-84ce-464e-b8c5-907c12abd9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'nav-title' and @href = 'index.html' and (text() = 'WebdriverUniversity.com (New Approach To Learning)' or . = 'WebdriverUniversity.com (New Approach To Learning)')]</value>
      <webElementGuid>5970ab1f-d5b1-4e0b-928e-2643e6df8ffd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
