<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header_GREENKARTFree Access to InterviewQue_8c5b1b</name>
   <tag></tag>
   <elementGuidId>b10b17c3-66f6-47a4-aacf-af03d2e13a45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>73292a25-48cf-4c62-aada-e3ec252e6acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GREENKARTFree Access to InterviewQues/ResumeAssistance/MaterialTop DealsFlight BookingItems:0Price:0You cart is empty!PROCEED TO CHECKOUT</value>
      <webElementGuid>2c7166fd-b4a6-418b-abde-4f99aab54bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/header[1]</value>
      <webElementGuid>a8ed636b-0d43-4c06-a3f0-998b6462c3eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header</value>
      <webElementGuid>a2feba7c-bdcd-41e6-bb68-e445dbd7cbb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header</value>
      <webElementGuid>ad296323-2f18-4c45-9b44-e781ef34285a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//header[(text() = 'GREENKARTFree Access to InterviewQues/ResumeAssistance/MaterialTop DealsFlight BookingItems:0Price:0You cart is empty!PROCEED TO CHECKOUT' or . = 'GREENKARTFree Access to InterviewQues/ResumeAssistance/MaterialTop DealsFlight BookingItems:0Price:0You cart is empty!PROCEED TO CHECKOUT')]</value>
      <webElementGuid>b3ac658c-0b4b-41a9-8f49-fc588c5e024c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
