<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_KART</name>
   <tag></tag>
   <elementGuidId>c2c79d83-a65d-49e5-9ce9-397620cc9dd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.redLogo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dabeff97-4a93-4563-a83b-126c9ab0d05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>redLogo</value>
      <webElementGuid>a92e3625-d8f6-45f2-8d0b-1fb07fb13533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KART</value>
      <webElementGuid>ea490b34-7b7d-402b-86a5-87ec1c3d587b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;container&quot;]/header[1]/div[@class=&quot;container&quot;]/div[@class=&quot;brand greenLogo&quot;]/span[@class=&quot;redLogo&quot;]</value>
      <webElementGuid>b21a9e07-a603-4d7c-8f24-2690dc361e60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div/span</value>
      <webElementGuid>cb56b339-5873-4f1e-8831-f9e0426e7d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Access to InterviewQues/ResumeAssistance/Material'])[1]/preceding::span[1]</value>
      <webElementGuid>3d345ba8-cc56-47ba-bf5d-6f7f7a3c4be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Deals'])[1]/preceding::span[1]</value>
      <webElementGuid>120af634-951b-446e-a2ea-7ff5804c7670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KART']/parent::*</value>
      <webElementGuid>470bb7cf-923f-4868-a3ad-c09922b34cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>4a9ed751-cdee-433f-8f24-6f3a749c50b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'KART' or . = 'KART')]</value>
      <webElementGuid>3abb46cc-6733-4bc0-aac7-3e3bbeefcc9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
