<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>[value=&quot;Angola&quot;]</description>
   <name>Angola</name>
   <tag></tag>
   <elementGuidId>e58681fe-41c9-4204-8a7d-f0ba7ae3551e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;Angola&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
